[package]
name = "ush-obfuscate"
version.workspace = true
edition.workspace = true
authors.workspace = true
include.workspace = true

[features]
default = []
obfuscate_aes = []
obfuscate_ref = []

[lib]
proc-macro = true

[dependencies]
base62 = {path = "../base62"}

# aes = "0.8.4"
block-padding = "0.4.2"
getrandom = "0.4.2"
hex = "0.4.3"
hex-literal = "1.1.0"
# regex = "1.12.2"
# sha2 = "0.10.9"

# Common
static_init = { workspace = true }

# Specific
quote = "1.0.45"
syn = {version = "2.0.117", features = ["full"]}
proc-macro2 = "1.0.106"
rand = "0.10.1"
