[package]
name = "unshell-payload"
edition = "2024"

# [features]
# obfuscate = ["unshell-obfuscate/obfuscate"]
# log = ["unshell-lib/log"]
# log_debug = ["unshell-lib/log_debug"]

# client = ["unshell-lib/client"]
# server = ["unshell-lib/server"]
# # server = ["unshell-lib/server"]


[dependencies]
# lazy_static = "1.5.0"
static_init = "1.0.4"

# unshell-lib = {path = "../unshell-lib", default-features = false}
unshell-obfuscate = {path = "../unshell-obfuscate"}

[profile.release]
# strip = true # Strip symbols from the binary
# opt-level = "z"  # Optimize for size
# lto = true # Link tree optimization
# codegen-units = 1
# panic = "abort"
# debug = false # Remove debug
# trim-paths="all"
