cargo-features = ["trim-paths"]

[package]
name = "unshell-payload"
edition = "2024"

# [lib]
# crate-type = ["cdylib"]

[features]
default = ["log"]
log = ["unshell/log", "server2/log"]
log_debug = ["unshell/log_debug", "server2/log_debug"]


# obfuscate = ["unshell-obfuscate/obfuscate"]
# log = ["unshell-lib/log"]
# log_debug = ["unshell-lib/log_debug"]

# client = ["unshell-lib/client"]
# server = ["unshell-lib/server"]
# # server = ["unshell-lib/server"]


[dependencies]

unshell.path = "../"
server2.path = "../core-modules/server2"
