[package]
name = "unshell-manager"
edition = "2024"

[features]
log = ["unshell/log"]
log_debug = ["log", "unshell/log_debug"]

obfuscate = ["unshell-obfuscate/obfuscate"]

# client = ["unshell-lib/client"]
# server = ["unshell-lib/server"]

[dependencies]
unshell = {path = "../", default-features = false}
unshell-obfuscate = {path = "../unshell-obfuscate"}

bincode = "2.0.1"
libc = "0.2.178"
libloading = "0.8.9"
rand = "0.9.2"
