[build]
filehash = false

# # Proxy /api/* to backend
# [[proxy]]
# backend = "http://localhost:8081"
# rewrite = "/api/"

# # Proxy /auth/* to backend
# [[proxy]]
# backend = "http://localhost:8081"
# rewrite = "/auth/"

[[proxy]]
backend = "http://localhost:3000/api"   # Address to proxy requests to
# ws = false                                # Use WebSocket for this proxy
# insecure = true                          # Disable certificate validation
# no_system_proxy = false                   # Disable system proxy
# rewrite = ""                              # Strip the given prefix off paths
# no_redirect = false                       # Disable following redirects of proxy responses
