[package]
name = "unshell-server"
# version = "0.1.0"
edition = "2024"

[features]
default=["log_debug"]
log_debug = ["unshell-lib/log_debug", "unshell-manager/log_debug"]

[dependencies]
unshell-lib = {path = "../unshell-lib", default-featues = false}
unshell-obfuscate = {path = "../unshell-obfuscate", default-featues = false}
unshell-manager = {path = "../unshell-manager", default-featues = false}

axum = "0.8.7"
axum-extra = {version="0.12.2", features = ["typed-header"]}
jsonwebtoken = {version = "10.2.0", features = ["aws_lc_rs"]}
serde = {version = "1.0.228", features = ["derive"]}
serde_json = "1.0.145"
tokio = {version="1.48.0", features = ["full"] }
bcrypt = "0.17.1"
chrono = "0.4.42"
static_init = "1.0.4"
clap = {version = "4.5.53", features = ["derive"]}
sled = "0.34.7"
toml = "0.9.9"
