[package]
name = "unshell-tui"
version.workspace = true
edition.workspace = true
description = "Ratatui terminal interface for UnShell"

[dependencies]
crossterm.workspace = true
ratatui.workspace = true
unshell = { workspace = true, features = ["interface_ratatui"] }

[lints.rust]
elided_lifetimes_in_paths = "warn"
future_incompatible = { level = "warn", priority = -1 }
nonstandard_style = { level = "warn", priority = -1 }
rust_2018_idioms = { level = "warn", priority = -1 }
rust_2021_prelude_collisions = "warn"
semicolon_in_expressions_from_macros = "warn"
unsafe_op_in_unsafe_fn = "warn"
unused_import_braces = "warn"
unused_lifetimes = "warn"
trivial_casts = "allow"
