cargo-features = ["trim-paths"]

[package]
name = "ush-payload"
edition = "2024"

[features]
default = ["log"]
log = ["unshell/log"]
log_debug = ["unshell/log_debug"]
obfuscate = ["unshell/obfuscate"]

[dependencies]
unshell.path = "../"
serde.workspace = true
serde_json.workspace = true
crossbeam-channel = "0.5.15"
thiserror = "2.0"
base64 = "0.22"
