[package]
name = "endpoint_test"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
include.workspace = true

[dependencies]
unshell = { workspace = true }
leaf-shell = { path = "../../unshell-leaves/leaf-shell" }

[[bin]]
name = "endpoint_test"
path = "src/main.rs"
test = false
