cargo-features = ["trim-paths"]

[package]
name = "testproj"
version = "0.1.0"
edition = "2024"


[lib]
crate-type = ["cdylib"]

[dependencies]


[profile.release]
strip = true # Strip symbols from the binary
opt-level = "z"  # Optimize for size
lto = true # Link tree optimization
codegen-units = 1
panic = "abort"
debug = false # Remove debug
trim-paths="all"
